"""Strict configuration types and resolution for VFE 4.0."""

from .resolve import resolve_config, resolve_h4_validation_config
from .schema import (
    ArtifactConfig,
    DataConfig,
    H3ValidationConfig,
    H4AllowanceConfig,
    H4BootstrapConfig,
    H4ConditionEnvelopeConfig,
    H4EnvironmentConfig,
    H4TimingConfig,
    H4TraversalConfig,
    H4ValidationConfig,
    H5ValidationConfig,
    InferenceConfig,
    ModelConfig,
    OptimizationConfig,
    RecognitionConfig,
    ResolvedConfig,
    RunConfig,
    ValidationConfig,
)

__all__ = [
    "ArtifactConfig",
    "DataConfig",
    "H3ValidationConfig",
    "H4AllowanceConfig",
    "H4BootstrapConfig",
    "H4ConditionEnvelopeConfig",
    "H4EnvironmentConfig",
    "H4TimingConfig",
    "H4TraversalConfig",
    "H4ValidationConfig",
    "H5ValidationConfig",
    "InferenceConfig",
    "ModelConfig",
    "OptimizationConfig",
    "RecognitionConfig",
    "ResolvedConfig",
    "RunConfig",
    "ValidationConfig",
    "resolve_config",
    "resolve_h4_validation_config",
]
