"""Production objectives for the frozen H1 reference calculation."""

from vfe4.objective.language_elbo import (
    CompleteLanguageELBOFactorTrace,
    ExactSourceMixtureLaw,
    ExpectationEvaluationMethod,
    FactorPartition,
    H7AuthenticatedEvaluation,
    LanguageElboExpectation,
    LiveEmissionExpectation,
    LiveEmissionExpectationContext,
    MixtureMode,
    MomentProjectedLaw,
    PriorVariant,
    RecognitionConditioningMode,
    RecognitionFamily,
    capture_h7_complete_language_elbo,
    evaluate_emission_only_ablation,
    require_h7_complete_factor_trace,
    require_source_law_for_endpoint,
)
from vfe4.types.h6 import (
    EmissionOnlyAblationTerms,
    H6EndpointLanguageElboTerms,
    H6FactorTerm,
    H6LanguageElboTerms,
)

from vfe4.objective.dependency_graph import (
    FactorDependencyGraph,
    build_h5_reference_dependency_graph,
    expected_affected_factors,
)

from vfe4.objective.h2_information import (
    H2ComponentDiagnostics,
    H2ComponentTerms,
    H2InformationEvaluation,
    RoundingInputs,
    evaluate_information_elbo,
)
from vfe4.objective.h1_local import evaluate_local_elbo
from vfe4.objective.h8_sparse import (
    evaluate_h8_sparse_objective,
    h8_emission_expectation,
)
from vfe4.objective.h1_monolithic import (
    MonolithicElboResult,
    evaluate_monolithic_elbo,
)
from vfe4.objective.h3_gaussian import (
    H3ObjectiveEvaluation,
    evaluate_h3_elbo,
    evaluate_h3_elbo_difference,
)
from vfe4.objective.h7_covariance import (
    H7_COMPLETE_LOCAL_TERM_IDS,
    H7_INDEPENDENT_H1_NORMALIZATION_IDENTITY_SHA256,
    H7_INDEPENDENT_H1_PRODUCER_IDENTITY_SHA256,
    H7_MATRIX_EVIDENCE_NOT_APPLICABLE_REASON,
    H7_MATRIX_SCORER_RESIDUAL_IDS,
    H7_POINTWISE_P_SHIFT_INVARIANT_ID,
    H7_POINTWISE_Q_SHIFT_INVARIANT_ID,
    H7IndependentH1EvidenceRecord,
    evaluate_h7_complete_covariance,
    evaluate_h7_law_pair_covariance,
    h7_joint_gaussian_kl,
    require_h7_complete_term_inventory,
    require_h7_matrix_scorer_residual_inventory,
)
from vfe4.objective.h5_complete import (
    CacheDisposition,
    CompleteElboEvaluation,
    CompleteElboEvaluator,
    FactorCacheEntry,
    FactorCacheKey,
    FactorEvaluationRecord,
    FactorInputHashRecord,
    StaleFactorCacheError,
    evaluate_h5_complete_elbo,
)
from vfe4.objective.h6_prediction_v3 import (
    ExactSourceMixtureEvaluationV3,
    H6ActiveParameterBlockV3,
    H6EvaluatedRecognitionLawV3,
    H6MixtureModeV3,
    H6ObjectivePartitionV3,
    H6ObjectiveTermV3,
    H6PredictionObjectiveEstimateV3,
    H6SourceRowEvaluationV3,
    H6TerminalComponentEvaluationV3,
    MomentProjectionEvaluationV3,
    evaluate_h6_no_latent_cross_entropy_v3,
    evaluate_h6_prediction_elbo_v3,
    project_terminal_mixture_v3,
)

__all__ = [
    "EmissionOnlyAblationTerms",
    "CompleteLanguageELBOFactorTrace",
    "ExactSourceMixtureEvaluationV3",
    "ExactSourceMixtureLaw",
    "ExpectationEvaluationMethod",
    "FactorPartition",
    "FactorDependencyGraph",
    "CacheDisposition",
    "CompleteElboEvaluation",
    "CompleteElboEvaluator",
    "FactorCacheEntry",
    "FactorCacheKey",
    "FactorEvaluationRecord",
    "FactorInputHashRecord",
    "H2ComponentDiagnostics",
    "H2ComponentTerms",
    "H2InformationEvaluation",
    "H3ObjectiveEvaluation",
    "H6ActiveParameterBlockV3",
    "H6EvaluatedRecognitionLawV3",
    "H6MixtureModeV3",
    "H6ObjectivePartitionV3",
    "H6ObjectiveTermV3",
    "H6PredictionObjectiveEstimateV3",
    "H6SourceRowEvaluationV3",
    "H6TerminalComponentEvaluationV3",
    "H7_COMPLETE_LOCAL_TERM_IDS",
    "H7_INDEPENDENT_H1_NORMALIZATION_IDENTITY_SHA256",
    "H7_INDEPENDENT_H1_PRODUCER_IDENTITY_SHA256",
    "H7_MATRIX_EVIDENCE_NOT_APPLICABLE_REASON",
    "H7_MATRIX_SCORER_RESIDUAL_IDS",
    "H7_POINTWISE_P_SHIFT_INVARIANT_ID",
    "H7_POINTWISE_Q_SHIFT_INVARIANT_ID",
    "H7IndependentH1EvidenceRecord",
    "H7AuthenticatedEvaluation",
    "H6FactorTerm",
    "H6EndpointLanguageElboTerms",
    "H6LanguageElboTerms",
    "LanguageElboExpectation",
    "LiveEmissionExpectation",
    "LiveEmissionExpectationContext",
    "MixtureMode",
    "MomentProjectedLaw",
    "MomentProjectionEvaluationV3",
    "PriorVariant",
    "MonolithicElboResult",
    "RoundingInputs",
    "RecognitionConditioningMode",
    "RecognitionFamily",
    "StaleFactorCacheError",
    "build_h5_reference_dependency_graph",
    "capture_h7_complete_language_elbo",
    "evaluate_information_elbo",
    "evaluate_emission_only_ablation",
    "evaluate_h3_elbo",
    "evaluate_h3_elbo_difference",
    "evaluate_h5_complete_elbo",
    "evaluate_h6_no_latent_cross_entropy_v3",
    "evaluate_h6_prediction_elbo_v3",
    "evaluate_h7_complete_covariance",
    "evaluate_h7_law_pair_covariance",
    "evaluate_local_elbo",
    "evaluate_h8_sparse_objective",
    "h8_emission_expectation",
    "project_terminal_mixture_v3",
    "evaluate_monolithic_elbo",
    "expected_affected_factors",
    "h7_joint_gaussian_kl",
    "require_h7_complete_term_inventory",
    "require_h7_complete_factor_trace",
    "require_h7_matrix_scorer_residual_inventory",
    "require_source_law_for_endpoint",
]
