"""Public canonical recording interfaces for WikiText-103 runs."""

from .failures import (
    FailureLogError,
    FailureRecord,
    append_failure,
    create_failure_record,
    recover_incomplete_failure_fragment,
    validate_failure_log,
)
from .metrics import (
    MetricDurabilityBackend,
    MetricLogError,
    UpdateControlRecord,
    WT103_REQUIRED_METRIC_FAMILIES,
    WT103_SOURCE_KL_DIAGNOSTIC_REASON,
    WT103_UNAVAILABLE_ESTIMATOR_BOUND_REASON,
    append_metric,
    applicable_metric,
    create_metric_record,
    export_metrics_csv,
    metrics_csv_bytes,
    metric_family_applicability,
    not_applicable_metric,
    recover_incomplete_metric_fragment,
    source_entropy_metrics,
    validate_metric_log,
    validate_required_metric_families,
)
from .tables import load_finalized_metric_rows

__all__ = [
    "FailureLogError",
    "FailureRecord",
    "MetricDurabilityBackend",
    "MetricLogError",
    "UpdateControlRecord",
    "WT103_REQUIRED_METRIC_FAMILIES",
    "WT103_SOURCE_KL_DIAGNOSTIC_REASON",
    "WT103_UNAVAILABLE_ESTIMATOR_BOUND_REASON",
    "append_failure",
    "append_metric",
    "applicable_metric",
    "create_failure_record",
    "create_metric_record",
    "export_metrics_csv",
    "load_finalized_metric_rows",
    "metric_family_applicability",
    "metrics_csv_bytes",
    "not_applicable_metric",
    "recover_incomplete_failure_fragment",
    "recover_incomplete_metric_fragment",
    "source_entropy_metrics",
    "validate_failure_log",
    "validate_metric_log",
    "validate_required_metric_families",
]
