"""H6 arm construction and deterministic capacity matching."""

from .arms import (
    ARM_MATRIX_ROWS,
    ARM_MATRIX_SHA256,
    ArmTargetFreeProposalAdapter,
    BuiltArm,
    CausalAutoregressiveModel,
    LatentLanguageArmModel,
    build_a0,
    build_a1,
    build_a2,
    build_a3,
    build_a4,
    build_a5,
    build_arm,
    literal_arm_semantic_payload,
    shared_a2_a5_semantic_payload,
)
from .matching import (
    ArmConfig,
    ArmMatrixRow,
    CapacityAllocation,
    FlopTerm,
    MatchingReport,
    OptimizerBinding,
    ParameterRoleRecord,
    arm_matrix_sha256,
    audit_arm_matching,
)

__all__ = [
    "ARM_MATRIX_ROWS",
    "ARM_MATRIX_SHA256",
    "ArmConfig",
    "ArmMatrixRow",
    "ArmTargetFreeProposalAdapter",
    "BuiltArm",
    "CapacityAllocation",
    "CausalAutoregressiveModel",
    "FlopTerm",
    "LatentLanguageArmModel",
    "MatchingReport",
    "OptimizerBinding",
    "ParameterRoleRecord",
    "arm_matrix_sha256",
    "audit_arm_matching",
    "build_a0",
    "build_a1",
    "build_a2",
    "build_a3",
    "build_a4",
    "build_a5",
    "build_arm",
    "literal_arm_semantic_payload",
    "shared_a2_a5_semantic_payload",
]
