"""Pure finalized-input figure loading and deterministic rendering."""

from .load import (
    FigureApplicabilityRow,
    FigureInputError,
    FigurePoint,
    FinalResultTable,
    LoadedFigureInputs,
    MetricSource,
    load_figure_inputs,
)
from .plots import (
    plot_complete_elbo_decomposition,
    plot_seed_variability,
    plot_source_entropy_effective_count,
    plot_spd_health,
    plot_terminal_prior_nll_ppl,
    plot_throughput_memory,
    plot_training_objective_and_validation,
    plot_update_acceptance,
)
from .render import (
    FigureDurabilityBackend,
    RenderedFigureSet,
    preflight_figure_output_formats,
    render_figure_set,
    validate_figure_output_root,
)
from .spec import (
    FigureExperimentIndexIdentity,
    FigureInputIdentity,
    FigureOutputIdentity,
    FigurePanelSpec,
    FigureResultRow,
    FigureSeriesSpec,
    FigureSetManifest,
    FigureSpec,
    FrozenFigureProvenance,
    REQUIRED_FIGURE_FUNCTIONS,
    WT103_FIGURE_PROVENANCE,
    default_figure_specs,
    figure_panel_applicability,
    figure_series_metric_names,
    validate_figure_registry,
)

__all__ = [
    "FigureApplicabilityRow",
    "FigureDurabilityBackend",
    "FigureExperimentIndexIdentity",
    "FigureInputError",
    "FigureInputIdentity",
    "FigureOutputIdentity",
    "FigurePanelSpec",
    "FigurePoint",
    "FigureResultRow",
    "FigureSeriesSpec",
    "FigureSetManifest",
    "FigureSpec",
    "FrozenFigureProvenance",
    "FinalResultTable",
    "LoadedFigureInputs",
    "MetricSource",
    "REQUIRED_FIGURE_FUNCTIONS",
    "RenderedFigureSet",
    "WT103_FIGURE_PROVENANCE",
    "default_figure_specs",
    "figure_panel_applicability",
    "figure_series_metric_names",
    "load_figure_inputs",
    "plot_complete_elbo_decomposition",
    "plot_seed_variability",
    "plot_source_entropy_effective_count",
    "plot_spd_health",
    "plot_terminal_prior_nll_ppl",
    "plot_throughput_memory",
    "plot_training_objective_and_validation",
    "plot_update_acceptance",
    "preflight_figure_output_formats",
    "render_figure_set",
    "validate_figure_output_root",
    "validate_figure_registry",
]
